source 'https://rubygems.org'
gem 'github-pages'
gem 'minima'
gem 'jekyll-paginate'
gem 'jekyll-gist'
gem 'jekyll-feed'
#gem 'minima-dude', :git => 'https://github.com/lildude/minima-dude'
#gem 'minima-dude', :path => '/Users/lildude/Sites/static/minima-dude'
